name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  licence-check:
    runs-on: ubuntu-latest
    container: python:3.7-alpine
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add tar curl bash g++
          pip install tox

      - name: Cache licence-check
        uses: actions/cache@v2
        with:
          path: /lc
          key: lcc

      - name: Check licence
        uses: zepben/licence-check-action@main
        with:
          PATH: src

      - name: Build and publish
        run: |
          tox
        shell: bash
