name: Deploy snapshot to Pypi

on:
  push:
    branches:
      - main
      - LTS/*
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: python:3.7

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install tox twine

      - name: Cache licence-check
        uses: actions/cache@v2
        with:
          path: /lc
          key: lcc

      - name: Check licence
        uses: zepben/licence-check-action@main
        with:
          LC_URL: ${{ secrets.LC_URL }}
          PATH: src

      - name: Build and publish
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          tox
          twine upload dist/*
        shell: bash

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false

  update-snapshot-version:
    needs: deploy
    runs-on: ubuntu-latest
    container: zepben/pipeline-basic:5.1.0
    env:
      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Work around git permission issue
        run: |
          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
          git config --global --add safe.directory /__w/$dname/$dname
        shell: sh

      - name: Update snapshot version
        run: |
          git pull origin $GITHUB_REF
          source /scripts/common.sh
          /scripts/update-version.sh --python --snapshot setup.py
        shell: bash
