name: Create Hotfix Branch

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g. 2.5 or 2.5.0) to create the branch in.'
        required: true
jobs:
  create-branch:
    runs-on: ubuntu-latest
    container: zepben/pipeline-basic
    env:
      NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_MAVEN_SNAPSHOT: ${{ secrets.NEXUS_MAVEN_SNAPSHOT }}
      NEXUS_MAVEN_RELEASE: ${{ secrets.NEXUS_MAVEN_RELEASE }}
      SLACK_NOTIFICATION: YES
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Hotfix branch
        run: |
          /scripts/create-branch.sh --hotfix ${{ github.event.inputs.version }}
          export BITBUCKET_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          /scripts/update-version.sh --python setup.py changelog.md
        shell: bash
