name: Python Library Snapshot

on:
  push:
    branches:
      - main
      - LTS/*
  workflow_dispatch:

jobs:
  run:
    uses: zepben/.github/.github/workflows/python-lib-snapshot.yml@main
    with:
      product-key: "python-sdk"   # Must be unique
      product-repo: "zepben/evolve-sdk-python"   # Must be unique
    secrets: inherit
