name: Python Library Snapshot

on:
  push:
    branches:
      - main
      - LTS/*
      - hotfix/*
  workflow_dispatch:

jobs:
  run:
    uses: zepben/.github/.github/workflows/python-lib-snapshot.yml@main
    secrets: inherit
